id: "default"
enabled: true
priority: 0
permission: ""
worlds:
  - "world"
regions: []

title-animation:
  enabled: true
  interval-ticks: 12
  frames:
    - "&#2F6BFF&lKaram SMP"

lines-animation:
  enabled: true
  interval-ticks: 20

lines:
  - ""
  - "&#00FF66$ &fMoney &#00FF66%balance%"
  - "&#B34DFF✦ &fShards &#C25CFF0K"
  - "&#FF4D4D🗡 &fKills &#FF4D4D%kills%"
  - "&#FFAA33☠ &fDeaths &#FFAA33%deaths%"
  - "&#0a8ee3⏳ &fKeyall &#0a8ee3 0m 0s"
  - "&#FFE45C⏱ &fPlaytime &#FFE45C%playtime%"
  - ""
  - "&#BFBFBFEU Central &#0a8ee3(%ping%ms)"
